nevermined-io/react-components

- .github/workflows/push-to-docs.yml
Updates the path it needs to push the docs to
Related to Issue https://github.com/nevermined-io/docs/issues/64
> fix push to docs path

- lib/package.json
- providers/package.json
- providers/src/metamask.tsx
avoid undefined errors from walletProvider if the user has not metamask installed
> Fix error with WalletProvider when not metamask

- lib/package.json
- providers/package.json
> package.json bump

- lib/tsconfig.json
- providers/babel.config.json
- providers/jest.config.js
- providers/nodemon.json
- providers/package.json
- providers/src/chain-config.ts
- providers/src/client.tsx
- providers/src/index.ts
- providers/tests/chainConfig.ts
- providers/tests/providers.spec.tsx
- providers/tsconfig.json
- providers/yarn.lock
update connectkit and dependencies
> update connectkit and dependencies

- lib/package.json
- lib/yarn.lock
- providers/package.json
update sdk-js and sdk-dtp versions
> update sdk-js and sdk-dtp versions

- .github/workflows/testing.yml
- lib/package.json
- lib/scripts/download-artifacts.sh
- lib/src/services/account.ts
- lib/yarn.lock
- providers/package.json
update dependencies and fix userProfile
> update dependencies and fix userProfile

- lib/src/services/asset.tsx
Adds optional publishing progress
> Publishing progress

- .github/workflows/testing-nightly.yml
- .github/workflows/testing.yml
- lib/integration-tests/catalog-dtp.spec.tsx
- lib/integration-tests/config.ts
- lib/package.json
- lib/src/services/asset.tsx
- lib/src/utils/dtp.ts
- lib/yarn.lock
- providers/package.json
remove set approve all and update dependencies
> remove set approve all

- lib/package.json
- lib/src/services/account.ts
- lib/src/types/index.ts
- lib/src/utils/marketplace_token.ts
- lib/unit-tests/mockups.ts
- providers/package.json
Fix `localstorage` and `updatedate` type error
> Fix localstorage and updatedate type error

- scripts/restructure_docs.sh
fix the script to restructure docs in order to push it
> fix push docs

- catalog/package.json
- catalog/src/services/asset.tsx
- providers/package.json
Adds optional publishing logic. This has already been merged in main https://github.com/nevermined-io/react-components/pull/243 but somehow it disappeared 😞
> Asset publishing event

- catalog/package.json
- providers/package.json
> fix: 1.1.8 versioning

- .github/workflows/push-to-docs.yml
- catalog/package.json
- catalog/src/catalog.tsx
- catalog/src/services/asset.tsx
- providers/package.json
looks like dispatching `sdk` doesn't propagate the update stated in the children component because of this I changed `useReducer` hook to `useState`
Close #272, Close #271
> Fix token generation

- catalog/package.json
- package.json
- providers/package.json
> Bump: sdk@1.3.6

- providers/package.json
> fix: update version in providers

- catalog/package.json
- providers/package.json
> fix: update version in catalog and provider

- catalog/package.json
- providers/package.json
- providers/src/chain-config.ts
> feat: support gnosis and chiado chains

- catalog/package.json
- package.json
- providers/package.json
- yarn.lock
> Using latest SDK and DTP

- catalog/package.json
- package.json
- providers/package.json
> Using SDK v1.13.16 and DTP v0.4.16

- catalog/package.json
- package.json
- providers/package.json
> feat: update to sdk v1.4.0

- catalog/package.json
- providers/package.json
- providers/src/chain-config.ts
> feat: support arbitrum networks and update sdk version

- catalog/package.json
- providers/package.json
> feat: update sdk to version 1.5.2
